---
- name: Domain Join
  hosts: "{{ linux_vms | default('all') }}"
  tasks:
    - name: Configure Resolvectl
      block:
        - name: Add Resolvers
          when: dns_servers is defined
          community.general.ini_file:
            path: /etc/systemd/resolved.conf
            section: Resolve
            option: DNS
            value: "{{ dns_servers | join(' ') }}"
            mode: u=rw,go=r
        - name: Add Domains
          community.general.ini_file:
            path: /etc/systemd/resolved.conf
            section: Resolve
            option: Domains
            value: "{{ domain }} ~."
            mode: u=rw,go=r

    - name: Install prereq packages
      ansible.builtin.package:
        name:
          - realmd
          - sssd
          - sssd-tools
          - libnss-sss
          - libpam-sss
          - adcli
          - samba-common-bin
          - oddjob
          - oddjob-mkhomedir
          - packagekit

    - name: Ensure home dirs get autocreated
      ansible.builtin.lineinfile:
        path: /etc/pam.d/common-session
        line: 'session optional  pam_mkhomedir.so skel=/etc/skel umask=077'
        regexp: >-
         ^\s+session\s+optional\s+pam_mkhomedir\.so\s+skel=\/etc\/skel\s+umask=077.*\s*$

    - name: Check to see if we're already in the domain
      ansible.builtin.command:
        cmd: realm list
      register: realm_status
      changed_when: false

    - name: Join domain and remove secrets
      block:
        - name: Join Domain
          when: domain not in realm_status.stdout_lines
          ansible.builtin.shell: >-
            set -o pipefail &&
            /bin/bash -c "echo {{ join_password }} |
            realm join --user={{ join_user }}
            {{ join_ou is defined |
            ansible.builtin.ternary('--computer-ou=' + join_ou, '') }}
            {{ domain }}"
          register: join_output
          changed_when: join_output.rc == 0
      always:
        - name: Remove join secrets
          ansible.builtin.file:
            path: /root/domain_join.yml
            state: absent

    - name: Don't require fqdns for users
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: "[domain/{{ domain }}]"
        option: use_fully_qualified_names
        value: 'False'
        mode: u=rw,go=
