---
- name: Set up prompts

  hosts: localhost

  connection: local
  vars:
    global_bashrc:
      alpine: /etc/bash/bashrc
      debian: /etc/bash.bashrc
      redhat: /etc/bashrc
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
    - name: Set bash prompt
      when: "'bash' in ansible_facts.packages"
      block:
        - name: Make a /usr/local/share/bash
          ansible.builtin.file:
            path: /usr/local/share/bash
            state: directory
            mode: "u=rwx,go=rx"
            owner: root
            group: root

        - name: Get git-prompt.sh
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-prompt.sh
            dest: /usr/local/share/bash/git-prompt.sh
            mode: "u=rw,go=r"
            owner: root
            group: root

        - name: Create colors file
          ansible.builtin.copy:
            src: files/colors.sh
            dest: /usr/local/share/bash/colors.sh
            mode: "u=rw,go=r"
            owner: root
            group: root

        - name: Configure git-prompt settings
          ansible.builtin.blockinfile:
            path: "{{ global_bashrc[(ansible_facts['os_family'] | lower)] }}"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - PROMPT"
            block: |
              GIT_PS1_SHOWUNTRACKEDFILES=true
              GIT_PS1_SHOWDIRTYSTATE=true
              source /usr/local/share/bash/colors.sh
              source /usr/local/share/bash/git-prompt.sh
              force_color_prompt=yes
        - name: Set prompt bash.bashrc
          ansible.builtin.lineinfile:
            path: "{{ global_bashrc[(ansible_facts['os_family'] | lower)] }}"
            regexp: "{{ item.reg }}"
            line: "{{ item.line }}"
            insertafter: EOF
          loop_control:
            label: "{{ item.label }}"
          loop:
            - label: "Prompt Command"
              reg: "^PROMPT_COMMAND=.*"
              line: "PROMPT_COMMAND='PS1_CMD1=$(__git_ps1 \" (%s)\")'"
            - label: "Prompt"
              reg: "^PS1=.*"
              line: >-
                PS1="[$?] ${Color_User}\\u${Yellow}@${Orange}\\h${Color_Off}:${LYellow}\\w${Color_Off}${PS1_CMD1}> "
        - name: Set prompt /etc/skel
          when: ansible_facts['os_family'] in ["Debian","RedHat"]
          ansible.builtin.lineinfile:
            path: /etc/skel/.bashrc
            regexp: "{{ item.reg }}"
            line: "{{ item.line }}"
            insertafter: EOF
          loop_control:
            label: "{{ item.label }}"
          loop:
            - label: "Prompt Command"
              reg: "^PROMPT_COMMAND=.*"
              line: "PROMPT_COMMAND='PS1_CMD1=$(__git_ps1 \" (%s)\")'"
            - label: "Prompt"
              reg: "^PS1=.*PS1_CMD1.*"
              line: >-
                PS1="[$?] ${Color_User}\\u${Yellow}@${Orange}\\h${Color_Off}:${LYellow}\\w${Color_Off}${PS1_CMD1}> "
        - name: Set add include to root .bashrc
          ansible.builtin.lineinfile:
            path: /root/.bashrc
            line: "source {{ global_bashrc[(ansible_facts['os_family'] | lower)] }}"
            insertafter: EOF
        - name: Set root shell to bash
          ansible.builtin.user:
            name: root
            shell: /bin/bash

    - name: Set zsh prompt
      when: "'zsh' in ansible_facts.packages"
      block:
        - name: Fix home and end keys
          ansible.builtin.blockinfile:
            path: /etc/zsh/zshrc
            marker: "#{mark} ANSIBLE MANAGED - fix_key_binds"
            block: |
              bindkey  "^[[1~"   beginning-of-line
              bindkey  "^[[4~"   end-of-line
            mode: 'u=rw,g=r,o=r'
            owner: root
            group: root
        - name: Get git-prompt.zsh
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/woefe/git-prompt.zsh/refs/heads/master/git-prompt.zsh
            dest: /usr/local/share/zsh/git-prompt.zsh
            mode: 'u=rw,g=r,o=r'
            owner: root
            group: root

        - name: Configure git-prompt to be imported
          ansible.builtin.lineinfile:
            path: /etc/zsh/zshrc
            regexp: '^source .*git-prompt.zsh$'
            line: "source /usr/local/share/zsh/git-prompt.zsh"
            state: present
            insertbefore: '^export (PS1|PROMPT)='
            mode: 'u=rw,g=r,o=r'
            owner: root
            group: root

        - name: Set prompt
          ansible.builtin.lineinfile:
            path: /etc/zsh/zshrc
            regexp: '^export (PS1|PROMPT)='
            line: >-
              {% raw %}export PROMPT='%0(?.%{%F{34}%}.%{%F{198}%})[%?]%{%f%} %(!.%{%F{196}%}.%{%F{34}%})%n%{%F{220}%}@%{%F{214}%}%m%{%f%}:%{%F{229}%}%~
              $(gitprompt)$%{%f%}> '{% endraw %}
            state: present
            mode: 'u=rw,g=r,o=r'
            owner: root
            group: root

    - name: Configure aliases
      ansible.builtin.copy:
        dest: /etc/profile.d/aliases.sh
        content: |
          alias ls='ls -a --color=auto'
          alias ll='ls -la'
        mode: "u=rw,go=r"
        owner: root
        group: root
