# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - stable
  push:
    branches:
      - main
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: arc-runner-set-forristalorg
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
